version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: chinese-app-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chinese_app
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: chinese-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:17-alpine
    container_name: chinese-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chinese_app_user
      POSTGRES_PASSWORD: chinese_app_password
      POSTGRES_DB: chinese_app
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  redis-data:
  postgres-data: