# Nixpacks configuration for Bun
[phases.setup]
nixPkgs = ["bun", "openssl"]
aptPkgs = ["curl", "unzip", "libssl-dev", "ca-certificates"]

[phases.install]
# Use frozen lockfile for consistent installs
cmds = ["bun install --frozen-lockfile"]

[phases.build]
# Build the Next.js application
# Generate Prisma client and build Next.js
cmds = [
  "echo 'Building with DATABASE_URL:' && echo $DATABASE_URL | head -c 30 && echo '...'",
  "echo 'Generating Prisma Client for production environment...'",
  "bunx prisma generate --schema=./prisma/schema.prisma",
  "echo 'Listing generated Prisma binaries:'",
  "ls -la src/generated/prisma/*.node || echo 'No .node files found'",
  "echo 'Building Next.js application...'",
  "bun run build"
]

[start]
# Start the production server
cmd = "bun run start"

[variables]
# Environment variables
NODE_ENV = "production"
# Ensure Bun uses production optimizations
BUN_ENV = "production"