// Mock dictionary data for common characters
export const mockDictionary: Record<string, { meaning: string; pinyin: string }> = {
  '我': { meaning: 'I, me', pinyin: 'wǒ' },
  '你': { meaning: 'you', pinyin: 'nǐ' },
  '他': { meaning: 'he, him', pinyin: 'tā' },
  '她': { meaning: 'she, her', pinyin: 'tā' },
  '們': { meaning: 'plural marker', pinyin: 'men' },
  '的': { meaning: 'possessive particle', pinyin: 'de' },
  '是': { meaning: 'to be', pinyin: 'shì' },
  '有': { meaning: 'to have', pinyin: 'yǒu' },
  '在': { meaning: 'at, in', pinyin: 'zài' },
  '不': { meaning: 'not', pinyin: 'bù' },
  '了': { meaning: 'completed action', pinyin: 'le' },
  '大': { meaning: 'big', pinyin: 'dà' },
  '小': { meaning: 'small', pinyin: 'xiǎo' },
  '中': { meaning: 'middle', pinyin: 'zhōng' },
  '人': { meaning: 'person', pinyin: 'rén' },
  '來': { meaning: 'to come', pinyin: 'lái' },
  '去': { meaning: 'to go', pinyin: 'qù' },
  '好': { meaning: 'good', pinyin: 'hǎo' },
  '嗎': { meaning: 'question particle', pinyin: 'ma' },
  '吃': { meaning: 'to eat', pinyin: 'chī' },
  '喝': { meaning: 'to drink', pinyin: 'hē' },
  '看': { meaning: 'to see', pinyin: 'kàn' },
  '說': { meaning: 'to say', pinyin: 'shuō' },
  '聽': { meaning: 'to listen', pinyin: 'tīng' },
  '寫': { meaning: 'to write', pinyin: 'xiě' },
  '讀': { meaning: 'to read', pinyin: 'dú' },
  '學': { meaning: 'to learn', pinyin: 'xué' },
  '愛': { meaning: 'to love', pinyin: 'ài' },
  '家': { meaning: 'home, family', pinyin: 'jiā' },
  '國': { meaning: 'country', pinyin: 'guó' },
};